package com.taxiapp.application.enums;

public enum AdminMenuOptions {
    ADD_POINTS,ADD_PATH,ADD_ADMINS,VIEW_ROUTE,VIEW_TRIPS,APPROVE_DRIVERS,VIEW_DRIVERS,VIEW_DRIVER_POSITION,SET_TAXI_PRICE,REMOVE_DRIVERS,QUIT
}
